ARG SABRE_4_IMAGE="linagora/esn-sabre:sabre-4_1_5-07-11-2025"

FROM ${SABRE_4_IMAGE}

ENV SCHEDULE_ASYNC=true

COPY src/test/resources/twake-calendar-side-service-conf/jwt_publickey /var/www/config/esn.key.pub