FROM tungtv202/twake-calendar-side-service:1111-amqp-add-request-uri-header

COPY src/test/resources/twake-calendar-side-service-conf/configuration.properties /root/conf/configuration.properties
COPY src/test/resources/twake-calendar-side-service-conf/opensearch.properties /root/conf/opensearch.properties
COPY src/test/resources/twake-calendar-side-service-conf/rabbitmq.properties /root/conf/rabbitmq.properties
COPY src/test/resources/twake-calendar-side-service-conf/webadmin.properties /root/conf/webadmin.properties
COPY src/test/resources/twake-calendar-side-service-conf/jwt_privatekey /root/conf/jwt_privatekey
COPY src/test/resources/twake-calendar-side-service-conf/jwt_publickey /root/conf/jwt_publickey
COPY src/test/resources/twake-calendar-side-service-conf/logback.xml /root/conf/logback.xml